# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cell.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncell.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\nPutRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\x0bGetResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\x0bPutResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x8d\x01\n\x04\x43\x65ll\x12-\n\x03Get\x12\x16.google.protobuf.Empty\x1a\x0c.GetResponse\"\x00\x12\"\n\x03Put\x12\x0b.PutRequest\x1a\x0c.PutResponse\"\x00\x12\x32\n\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x0c.GetResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cell_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PUTREQUEST']._serialized_start=43
  _globals['_PUTREQUEST']._serialized_end=69
  _globals['_GETRESPONSE']._serialized_start=71
  _globals['_GETRESPONSE']._serialized_end=98
  _globals['_PUTRESPONSE']._serialized_start=100
  _globals['_PUTRESPONSE']._serialized_end=129
  _globals['_CELL']._serialized_start=132
  _globals['_CELL']._serialized_end=273
# @@protoc_insertion_point(module_scope)
